/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterStudentRouteImport } from './routes/register/student'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardMentorRouteImport } from './routes/dashboard/mentor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApplyMentorRouteImport } from './routes/apply/mentor'
import { Route as ApiAnnouncementsRouteImport } from './routes/api/announcements'
import { Route as ApiRegisterStudentRouteImport } from './routes/api/register/student'
import { Route as ApiMentorsDirectoryRouteImport } from './routes/api/mentors/directory'
import { Route as ApiApplicationsMentorRouteImport } from './routes/api/applications/mentor'
import { Route as ApiAnnouncementsIdRouteImport } from './routes/api/announcements.$id'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiMentorsProfileUserIdRouteImport } from './routes/api/mentors/profile.$userId'
import { Route as ApiApplicationsMentorIdReviewRouteImport } from './routes/api/applications/mentor.$id.review'

const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/dashboard/mentor',
  path: '/dashboard/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorRoute = ApplyMentorRouteImport.update({
  id: '/apply/mentor',
  path: '/apply/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsRoute = ApiAnnouncementsRouteImport.update({
  id: '/api/announcements',
  path: '/api/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterStudentRoute = ApiRegisterStudentRouteImport.update({
  id: '/api/register/student',
  path: '/api/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsDirectoryRoute = ApiMentorsDirectoryRouteImport.update({
  id: '/api/mentors/directory',
  path: '/api/mentors/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsMentorRoute = ApiApplicationsMentorRouteImport.update({
  id: '/api/applications/mentor',
  path: '/api/applications/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsIdRoute = ApiAnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAnnouncementsRoute,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsProfileUserIdRoute = ApiMentorsProfileUserIdRouteImport.update({
  id: '/api/mentors/profile/$userId',
  path: '/api/mentors/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsMentorIdReviewRoute =
  ApiApplicationsMentorIdReviewRouteImport.update({
    id: '/$id/review',
    path: '/$id/review',
    getParentRoute: () => ApiApplicationsMentorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRouteWithChildren
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/applications/mentor/$id/review': typeof ApiApplicationsMentorIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRouteWithChildren
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/applications/mentor/$id/review': typeof ApiApplicationsMentorIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRouteWithChildren
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/applications/mentor/$id/review': typeof ApiApplicationsMentorIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mentors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/stats'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/applications/mentor/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mentors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/stats'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/applications/mentor/$id/review'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mentors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/stats'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/applications/mentor/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  ApiAnnouncementsRoute: typeof ApiAnnouncementsRouteWithChildren
  ApplyMentorRoute: typeof ApplyMentorRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiApplicationsMentorRoute: typeof ApiApplicationsMentorRouteWithChildren
  ApiMentorsDirectoryRoute: typeof ApiMentorsDirectoryRoute
  ApiRegisterStudentRoute: typeof ApiRegisterStudentRoute
  ApiMentorsProfileUserIdRoute: typeof ApiMentorsProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/mentor': {
      id: '/apply/mentor'
      path: '/apply/mentor'
      fullPath: '/apply/mentor'
      preLoaderRoute: typeof ApplyMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements': {
      id: '/api/announcements'
      path: '/api/announcements'
      fullPath: '/api/announcements'
      preLoaderRoute: typeof ApiAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register/student': {
      id: '/api/register/student'
      path: '/api/register/student'
      fullPath: '/api/register/student'
      preLoaderRoute: typeof ApiRegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/directory': {
      id: '/api/mentors/directory'
      path: '/api/mentors/directory'
      fullPath: '/api/mentors/directory'
      preLoaderRoute: typeof ApiMentorsDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/mentor': {
      id: '/api/applications/mentor'
      path: '/api/applications/mentor'
      fullPath: '/api/applications/mentor'
      preLoaderRoute: typeof ApiApplicationsMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements/$id': {
      id: '/api/announcements/$id'
      path: '/$id'
      fullPath: '/api/announcements/$id'
      preLoaderRoute: typeof ApiAnnouncementsIdRouteImport
      parentRoute: typeof ApiAnnouncementsRoute
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/profile/$userId': {
      id: '/api/mentors/profile/$userId'
      path: '/api/mentors/profile/$userId'
      fullPath: '/api/mentors/profile/$userId'
      preLoaderRoute: typeof ApiMentorsProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/mentor/$id/review': {
      id: '/api/applications/mentor/$id/review'
      path: '/$id/review'
      fullPath: '/api/applications/mentor/$id/review'
      preLoaderRoute: typeof ApiApplicationsMentorIdReviewRouteImport
      parentRoute: typeof ApiApplicationsMentorRoute
    }
  }
}

interface ApiAnnouncementsRouteChildren {
  ApiAnnouncementsIdRoute: typeof ApiAnnouncementsIdRoute
}

const ApiAnnouncementsRouteChildren: ApiAnnouncementsRouteChildren = {
  ApiAnnouncementsIdRoute: ApiAnnouncementsIdRoute,
}

const ApiAnnouncementsRouteWithChildren =
  ApiAnnouncementsRoute._addFileChildren(ApiAnnouncementsRouteChildren)

interface ApiApplicationsMentorRouteChildren {
  ApiApplicationsMentorIdReviewRoute: typeof ApiApplicationsMentorIdReviewRoute
}

const ApiApplicationsMentorRouteChildren: ApiApplicationsMentorRouteChildren = {
  ApiApplicationsMentorIdReviewRoute: ApiApplicationsMentorIdReviewRoute,
}

const ApiApplicationsMentorRouteWithChildren =
  ApiApplicationsMentorRoute._addFileChildren(
    ApiApplicationsMentorRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  ApiAnnouncementsRoute: ApiAnnouncementsRouteWithChildren,
  ApplyMentorRoute: ApplyMentorRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiApplicationsMentorRoute: ApiApplicationsMentorRouteWithChildren,
  ApiMentorsDirectoryRoute: ApiMentorsDirectoryRoute,
  ApiRegisterStudentRoute: ApiRegisterStudentRoute,
  ApiMentorsProfileUserIdRoute: ApiMentorsProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
