CREATE TABLE "ambassadors" (
	"id" serial PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"title" text DEFAULT 'Student Ambassador' NOT NULL,
	"school" text,
	"country" text,
	"city" text,
	"graduation_year" text,
	"bio" text DEFAULT '' NOT NULL,
	"achievements" text DEFAULT '' NOT NULL,
	"subjects" text DEFAULT '' NOT NULL,
	"languages" text DEFAULT '' NOT NULL,
	"photo_url" text,
	"contact_email" text,
	"instagram" text,
	"telegram" text,
	"whatsapp" text,
	"linkedin" text,
	"website" text,
	"featured" boolean DEFAULT false NOT NULL,
	"is_public" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
