/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterStudentRouteImport } from './routes/register/student'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardMentorRouteImport } from './routes/dashboard/mentor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApplyMentorRouteImport } from './routes/apply/mentor'
import { Route as ApiAnnouncementsRouteImport } from './routes/api/announcements'
import { Route as ApiAmbassadorsRouteImport } from './routes/api/ambassadors'
import { Route as ApiAmbassadorPhotosRouteImport } from './routes/api/ambassador-photos'
import { Route as ApiStudentsSessionsRouteImport } from './routes/api/students/sessions'
import { Route as ApiRegisterStudentRouteImport } from './routes/api/register/student'
import { Route as ApiMentorsSessionsRouteImport } from './routes/api/mentors/sessions'
import { Route as ApiMentorsDirectoryRouteImport } from './routes/api/mentors/directory'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant/chat'
import { Route as ApiApplicationsMentorRouteImport } from './routes/api/applications/mentor'
import { Route as ApiAnnouncementsIdRouteImport } from './routes/api/announcements.$id'
import { Route as ApiAmbassadorsIdRouteImport } from './routes/api/ambassadors.$id'
import { Route as ApiAmbassadorPhotosKeyRouteImport } from './routes/api/ambassador-photos.$key'
import { Route as ApiAdminStudentsRouteImport } from './routes/api/admin/students'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSessionsRouteImport } from './routes/api/admin/sessions'
import { Route as ApiAdminMentorsRouteImport } from './routes/api/admin/mentors'
import { Route as ApiMentorsSessionsIdRouteImport } from './routes/api/mentors/sessions.$id'
import { Route as ApiMentorsProfileUserIdRouteImport } from './routes/api/mentors/profile.$userId'
import { Route as ApiMentorsSessionsIdEvidenceRouteImport } from './routes/api/mentors/sessions.$id.evidence'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/dashboard/mentor',
  path: '/dashboard/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorRoute = ApplyMentorRouteImport.update({
  id: '/apply/mentor',
  path: '/apply/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsRoute = ApiAnnouncementsRouteImport.update({
  id: '/api/announcements',
  path: '/api/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAmbassadorsRoute = ApiAmbassadorsRouteImport.update({
  id: '/api/ambassadors',
  path: '/api/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAmbassadorPhotosRoute = ApiAmbassadorPhotosRouteImport.update({
  id: '/api/ambassador-photos',
  path: '/api/ambassador-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsSessionsRoute = ApiStudentsSessionsRouteImport.update({
  id: '/api/students/sessions',
  path: '/api/students/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterStudentRoute = ApiRegisterStudentRouteImport.update({
  id: '/api/register/student',
  path: '/api/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsSessionsRoute = ApiMentorsSessionsRouteImport.update({
  id: '/api/mentors/sessions',
  path: '/api/mentors/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsDirectoryRoute = ApiMentorsDirectoryRouteImport.update({
  id: '/api/mentors/directory',
  path: '/api/mentors/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant/chat',
  path: '/api/assistant/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsMentorRoute = ApiApplicationsMentorRouteImport.update({
  id: '/api/applications/mentor',
  path: '/api/applications/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsIdRoute = ApiAnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAnnouncementsRoute,
} as any)
const ApiAmbassadorsIdRoute = ApiAmbassadorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAmbassadorsRoute,
} as any)
const ApiAmbassadorPhotosKeyRoute = ApiAmbassadorPhotosKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiAmbassadorPhotosRoute,
} as any)
const ApiAdminStudentsRoute = ApiAdminStudentsRouteImport.update({
  id: '/api/admin/students',
  path: '/api/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionsRoute = ApiAdminSessionsRouteImport.update({
  id: '/api/admin/sessions',
  path: '/api/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMentorsRoute = ApiAdminMentorsRouteImport.update({
  id: '/api/admin/mentors',
  path: '/api/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsSessionsIdRoute = ApiMentorsSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMentorsSessionsRoute,
} as any)
const ApiMentorsProfileUserIdRoute = ApiMentorsProfileUserIdRouteImport.update({
  id: '/api/mentors/profile/$userId',
  path: '/api/mentors/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsSessionsIdEvidenceRoute =
  ApiMentorsSessionsIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => ApiMentorsSessionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/assistant': typeof AssistantRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ambassador-photos': typeof ApiAmbassadorPhotosRouteWithChildren
  '/api/ambassadors': typeof ApiAmbassadorsRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/sessions': typeof ApiAdminSessionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/ambassador-photos/$key': typeof ApiAmbassadorPhotosKeyRoute
  '/api/ambassadors/$id': typeof ApiAmbassadorsIdRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/students/sessions': typeof ApiStudentsSessionsRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRouteWithChildren
  '/api/mentors/sessions/$id/evidence': typeof ApiMentorsSessionsIdEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/assistant': typeof AssistantRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ambassador-photos': typeof ApiAmbassadorPhotosRouteWithChildren
  '/api/ambassadors': typeof ApiAmbassadorsRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/sessions': typeof ApiAdminSessionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/ambassador-photos/$key': typeof ApiAmbassadorPhotosKeyRoute
  '/api/ambassadors/$id': typeof ApiAmbassadorsIdRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/students/sessions': typeof ApiStudentsSessionsRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRouteWithChildren
  '/api/mentors/sessions/$id/evidence': typeof ApiMentorsSessionsIdEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/assistant': typeof AssistantRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ambassador-photos': typeof ApiAmbassadorPhotosRouteWithChildren
  '/api/ambassadors': typeof ApiAmbassadorsRouteWithChildren
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/sessions': typeof ApiAdminSessionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/ambassador-photos/$key': typeof ApiAmbassadorPhotosKeyRoute
  '/api/ambassadors/$id': typeof ApiAmbassadorsIdRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/students/sessions': typeof ApiStudentsSessionsRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRouteWithChildren
  '/api/mentors/sessions/$id/evidence': typeof ApiMentorsSessionsIdEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassadors'
    | '/assistant'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/ambassador-photos'
    | '/api/ambassadors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/sessions'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/ambassador-photos/$key'
    | '/api/ambassadors/$id'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/assistant/chat'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/students/sessions'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
    | '/api/mentors/sessions/$id/evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambassadors'
    | '/assistant'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/ambassador-photos'
    | '/api/ambassadors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/sessions'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/ambassador-photos/$key'
    | '/api/ambassadors/$id'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/assistant/chat'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/students/sessions'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
    | '/api/mentors/sessions/$id/evidence'
  id:
    | '__root__'
    | '/'
    | '/ambassadors'
    | '/assistant'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/ambassador-photos'
    | '/api/ambassadors'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/sessions'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/ambassador-photos/$key'
    | '/api/ambassadors/$id'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/assistant/chat'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/students/sessions'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
    | '/api/mentors/sessions/$id/evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  AssistantRoute: typeof AssistantRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAmbassadorPhotosRoute: typeof ApiAmbassadorPhotosRouteWithChildren
  ApiAmbassadorsRoute: typeof ApiAmbassadorsRouteWithChildren
  ApiAnnouncementsRoute: typeof ApiAnnouncementsRouteWithChildren
  ApplyMentorRoute: typeof ApplyMentorRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  ApiAdminMentorsRoute: typeof ApiAdminMentorsRoute
  ApiAdminSessionsRoute: typeof ApiAdminSessionsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminStudentsRoute: typeof ApiAdminStudentsRoute
  ApiApplicationsMentorRoute: typeof ApiApplicationsMentorRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiMentorsDirectoryRoute: typeof ApiMentorsDirectoryRoute
  ApiMentorsSessionsRoute: typeof ApiMentorsSessionsRouteWithChildren
  ApiRegisterStudentRoute: typeof ApiRegisterStudentRoute
  ApiStudentsSessionsRoute: typeof ApiStudentsSessionsRoute
  ApiMentorsProfileUserIdRoute: typeof ApiMentorsProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/mentor': {
      id: '/apply/mentor'
      path: '/apply/mentor'
      fullPath: '/apply/mentor'
      preLoaderRoute: typeof ApplyMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements': {
      id: '/api/announcements'
      path: '/api/announcements'
      fullPath: '/api/announcements'
      preLoaderRoute: typeof ApiAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ambassadors': {
      id: '/api/ambassadors'
      path: '/api/ambassadors'
      fullPath: '/api/ambassadors'
      preLoaderRoute: typeof ApiAmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ambassador-photos': {
      id: '/api/ambassador-photos'
      path: '/api/ambassador-photos'
      fullPath: '/api/ambassador-photos'
      preLoaderRoute: typeof ApiAmbassadorPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/sessions': {
      id: '/api/students/sessions'
      path: '/api/students/sessions'
      fullPath: '/api/students/sessions'
      preLoaderRoute: typeof ApiStudentsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register/student': {
      id: '/api/register/student'
      path: '/api/register/student'
      fullPath: '/api/register/student'
      preLoaderRoute: typeof ApiRegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/sessions': {
      id: '/api/mentors/sessions'
      path: '/api/mentors/sessions'
      fullPath: '/api/mentors/sessions'
      preLoaderRoute: typeof ApiMentorsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/directory': {
      id: '/api/mentors/directory'
      path: '/api/mentors/directory'
      fullPath: '/api/mentors/directory'
      preLoaderRoute: typeof ApiMentorsDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/api/assistant/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/mentor': {
      id: '/api/applications/mentor'
      path: '/api/applications/mentor'
      fullPath: '/api/applications/mentor'
      preLoaderRoute: typeof ApiApplicationsMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements/$id': {
      id: '/api/announcements/$id'
      path: '/$id'
      fullPath: '/api/announcements/$id'
      preLoaderRoute: typeof ApiAnnouncementsIdRouteImport
      parentRoute: typeof ApiAnnouncementsRoute
    }
    '/api/ambassadors/$id': {
      id: '/api/ambassadors/$id'
      path: '/$id'
      fullPath: '/api/ambassadors/$id'
      preLoaderRoute: typeof ApiAmbassadorsIdRouteImport
      parentRoute: typeof ApiAmbassadorsRoute
    }
    '/api/ambassador-photos/$key': {
      id: '/api/ambassador-photos/$key'
      path: '/$key'
      fullPath: '/api/ambassador-photos/$key'
      preLoaderRoute: typeof ApiAmbassadorPhotosKeyRouteImport
      parentRoute: typeof ApiAmbassadorPhotosRoute
    }
    '/api/admin/students': {
      id: '/api/admin/students'
      path: '/api/admin/students'
      fullPath: '/api/admin/students'
      preLoaderRoute: typeof ApiAdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sessions': {
      id: '/api/admin/sessions'
      path: '/api/admin/sessions'
      fullPath: '/api/admin/sessions'
      preLoaderRoute: typeof ApiAdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mentors': {
      id: '/api/admin/mentors'
      path: '/api/admin/mentors'
      fullPath: '/api/admin/mentors'
      preLoaderRoute: typeof ApiAdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/sessions/$id': {
      id: '/api/mentors/sessions/$id'
      path: '/$id'
      fullPath: '/api/mentors/sessions/$id'
      preLoaderRoute: typeof ApiMentorsSessionsIdRouteImport
      parentRoute: typeof ApiMentorsSessionsRoute
    }
    '/api/mentors/profile/$userId': {
      id: '/api/mentors/profile/$userId'
      path: '/api/mentors/profile/$userId'
      fullPath: '/api/mentors/profile/$userId'
      preLoaderRoute: typeof ApiMentorsProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/sessions/$id/evidence': {
      id: '/api/mentors/sessions/$id/evidence'
      path: '/evidence'
      fullPath: '/api/mentors/sessions/$id/evidence'
      preLoaderRoute: typeof ApiMentorsSessionsIdEvidenceRouteImport
      parentRoute: typeof ApiMentorsSessionsIdRoute
    }
  }
}

interface ApiAmbassadorPhotosRouteChildren {
  ApiAmbassadorPhotosKeyRoute: typeof ApiAmbassadorPhotosKeyRoute
}

const ApiAmbassadorPhotosRouteChildren: ApiAmbassadorPhotosRouteChildren = {
  ApiAmbassadorPhotosKeyRoute: ApiAmbassadorPhotosKeyRoute,
}

const ApiAmbassadorPhotosRouteWithChildren =
  ApiAmbassadorPhotosRoute._addFileChildren(ApiAmbassadorPhotosRouteChildren)

interface ApiAmbassadorsRouteChildren {
  ApiAmbassadorsIdRoute: typeof ApiAmbassadorsIdRoute
}

const ApiAmbassadorsRouteChildren: ApiAmbassadorsRouteChildren = {
  ApiAmbassadorsIdRoute: ApiAmbassadorsIdRoute,
}

const ApiAmbassadorsRouteWithChildren = ApiAmbassadorsRoute._addFileChildren(
  ApiAmbassadorsRouteChildren,
)

interface ApiAnnouncementsRouteChildren {
  ApiAnnouncementsIdRoute: typeof ApiAnnouncementsIdRoute
}

const ApiAnnouncementsRouteChildren: ApiAnnouncementsRouteChildren = {
  ApiAnnouncementsIdRoute: ApiAnnouncementsIdRoute,
}

const ApiAnnouncementsRouteWithChildren =
  ApiAnnouncementsRoute._addFileChildren(ApiAnnouncementsRouteChildren)

interface ApiMentorsSessionsIdRouteChildren {
  ApiMentorsSessionsIdEvidenceRoute: typeof ApiMentorsSessionsIdEvidenceRoute
}

const ApiMentorsSessionsIdRouteChildren: ApiMentorsSessionsIdRouteChildren = {
  ApiMentorsSessionsIdEvidenceRoute: ApiMentorsSessionsIdEvidenceRoute,
}

const ApiMentorsSessionsIdRouteWithChildren =
  ApiMentorsSessionsIdRoute._addFileChildren(ApiMentorsSessionsIdRouteChildren)

interface ApiMentorsSessionsRouteChildren {
  ApiMentorsSessionsIdRoute: typeof ApiMentorsSessionsIdRouteWithChildren
}

const ApiMentorsSessionsRouteChildren: ApiMentorsSessionsRouteChildren = {
  ApiMentorsSessionsIdRoute: ApiMentorsSessionsIdRouteWithChildren,
}

const ApiMentorsSessionsRouteWithChildren =
  ApiMentorsSessionsRoute._addFileChildren(ApiMentorsSessionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  AssistantRoute: AssistantRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAmbassadorPhotosRoute: ApiAmbassadorPhotosRouteWithChildren,
  ApiAmbassadorsRoute: ApiAmbassadorsRouteWithChildren,
  ApiAnnouncementsRoute: ApiAnnouncementsRouteWithChildren,
  ApplyMentorRoute: ApplyMentorRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  ApiAdminMentorsRoute: ApiAdminMentorsRoute,
  ApiAdminSessionsRoute: ApiAdminSessionsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminStudentsRoute: ApiAdminStudentsRoute,
  ApiApplicationsMentorRoute: ApiApplicationsMentorRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiMentorsDirectoryRoute: ApiMentorsDirectoryRoute,
  ApiMentorsSessionsRoute: ApiMentorsSessionsRouteWithChildren,
  ApiRegisterStudentRoute: ApiRegisterStudentRoute,
  ApiStudentsSessionsRoute: ApiStudentsSessionsRoute,
  ApiMentorsProfileUserIdRoute: ApiMentorsProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
