/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterStudentRouteImport } from './routes/register/student'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardMentorRouteImport } from './routes/dashboard/mentor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApplyMentorRouteImport } from './routes/apply/mentor'
import { Route as ApiAnnouncementsRouteImport } from './routes/api/announcements'
import { Route as ApiRegisterStudentRouteImport } from './routes/api/register/student'
import { Route as ApiMentorsSessionsRouteImport } from './routes/api/mentors/sessions'
import { Route as ApiMentorsDirectoryRouteImport } from './routes/api/mentors/directory'
import { Route as ApiApplicationsMentorRouteImport } from './routes/api/applications/mentor'
import { Route as ApiAnnouncementsIdRouteImport } from './routes/api/announcements.$id'
import { Route as ApiAdminStudentsRouteImport } from './routes/api/admin/students'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminMentorsRouteImport } from './routes/api/admin/mentors'
import { Route as ApiMentorsSessionsIdRouteImport } from './routes/api/mentors/sessions.$id'
import { Route as ApiMentorsProfileUserIdRouteImport } from './routes/api/mentors/profile.$userId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/dashboard/mentor',
  path: '/dashboard/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorRoute = ApplyMentorRouteImport.update({
  id: '/apply/mentor',
  path: '/apply/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsRoute = ApiAnnouncementsRouteImport.update({
  id: '/api/announcements',
  path: '/api/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterStudentRoute = ApiRegisterStudentRouteImport.update({
  id: '/api/register/student',
  path: '/api/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsSessionsRoute = ApiMentorsSessionsRouteImport.update({
  id: '/api/mentors/sessions',
  path: '/api/mentors/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsDirectoryRoute = ApiMentorsDirectoryRouteImport.update({
  id: '/api/mentors/directory',
  path: '/api/mentors/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsMentorRoute = ApiApplicationsMentorRouteImport.update({
  id: '/api/applications/mentor',
  path: '/api/applications/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsIdRoute = ApiAnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAnnouncementsRoute,
} as any)
const ApiAdminStudentsRoute = ApiAdminStudentsRouteImport.update({
  id: '/api/admin/students',
  path: '/api/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMentorsRoute = ApiAdminMentorsRouteImport.update({
  id: '/api/admin/mentors',
  path: '/api/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorsSessionsIdRoute = ApiMentorsSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMentorsSessionsRoute,
} as any)
const ApiMentorsProfileUserIdRoute = ApiMentorsProfileUserIdRouteImport.update({
  id: '/api/mentors/profile/$userId',
  path: '/api/mentors/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/announcements': typeof ApiAnnouncementsRouteWithChildren
  '/apply/mentor': typeof ApplyMentorRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/register/student': typeof RegisterStudentRoute
  '/api/admin/mentors': typeof ApiAdminMentorsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/announcements/$id': typeof ApiAnnouncementsIdRoute
  '/api/applications/mentor': typeof ApiApplicationsMentorRoute
  '/api/mentors/directory': typeof ApiMentorsDirectoryRoute
  '/api/mentors/sessions': typeof ApiMentorsSessionsRouteWithChildren
  '/api/register/student': typeof ApiRegisterStudentRoute
  '/api/mentors/profile/$userId': typeof ApiMentorsProfileUserIdRoute
  '/api/mentors/sessions/$id': typeof ApiMentorsSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mentors'
    | '/reset-password'
    | '/api/announcements'
    | '/apply/mentor'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/student'
    | '/register/student'
    | '/api/admin/mentors'
    | '/api/admin/stats'
    | '/api/admin/students'
    | '/api/announcements/$id'
    | '/api/applications/mentor'
    | '/api/mentors/directory'
    | '/api/mentors/sessions'
    | '/api/register/student'
    | '/api/mentors/profile/$userId'
    | '/api/mentors/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAnnouncementsRoute: typeof ApiAnnouncementsRouteWithChildren
  ApplyMentorRoute: typeof ApplyMentorRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  ApiAdminMentorsRoute: typeof ApiAdminMentorsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminStudentsRoute: typeof ApiAdminStudentsRoute
  ApiApplicationsMentorRoute: typeof ApiApplicationsMentorRoute
  ApiMentorsDirectoryRoute: typeof ApiMentorsDirectoryRoute
  ApiMentorsSessionsRoute: typeof ApiMentorsSessionsRouteWithChildren
  ApiRegisterStudentRoute: typeof ApiRegisterStudentRoute
  ApiMentorsProfileUserIdRoute: typeof ApiMentorsProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/mentor': {
      id: '/apply/mentor'
      path: '/apply/mentor'
      fullPath: '/apply/mentor'
      preLoaderRoute: typeof ApplyMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements': {
      id: '/api/announcements'
      path: '/api/announcements'
      fullPath: '/api/announcements'
      preLoaderRoute: typeof ApiAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register/student': {
      id: '/api/register/student'
      path: '/api/register/student'
      fullPath: '/api/register/student'
      preLoaderRoute: typeof ApiRegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/sessions': {
      id: '/api/mentors/sessions'
      path: '/api/mentors/sessions'
      fullPath: '/api/mentors/sessions'
      preLoaderRoute: typeof ApiMentorsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/directory': {
      id: '/api/mentors/directory'
      path: '/api/mentors/directory'
      fullPath: '/api/mentors/directory'
      preLoaderRoute: typeof ApiMentorsDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/mentor': {
      id: '/api/applications/mentor'
      path: '/api/applications/mentor'
      fullPath: '/api/applications/mentor'
      preLoaderRoute: typeof ApiApplicationsMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements/$id': {
      id: '/api/announcements/$id'
      path: '/$id'
      fullPath: '/api/announcements/$id'
      preLoaderRoute: typeof ApiAnnouncementsIdRouteImport
      parentRoute: typeof ApiAnnouncementsRoute
    }
    '/api/admin/students': {
      id: '/api/admin/students'
      path: '/api/admin/students'
      fullPath: '/api/admin/students'
      preLoaderRoute: typeof ApiAdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mentors': {
      id: '/api/admin/mentors'
      path: '/api/admin/mentors'
      fullPath: '/api/admin/mentors'
      preLoaderRoute: typeof ApiAdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentors/sessions/$id': {
      id: '/api/mentors/sessions/$id'
      path: '/$id'
      fullPath: '/api/mentors/sessions/$id'
      preLoaderRoute: typeof ApiMentorsSessionsIdRouteImport
      parentRoute: typeof ApiMentorsSessionsRoute
    }
    '/api/mentors/profile/$userId': {
      id: '/api/mentors/profile/$userId'
      path: '/api/mentors/profile/$userId'
      fullPath: '/api/mentors/profile/$userId'
      preLoaderRoute: typeof ApiMentorsProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAnnouncementsRouteChildren {
  ApiAnnouncementsIdRoute: typeof ApiAnnouncementsIdRoute
}

const ApiAnnouncementsRouteChildren: ApiAnnouncementsRouteChildren = {
  ApiAnnouncementsIdRoute: ApiAnnouncementsIdRoute,
}

const ApiAnnouncementsRouteWithChildren =
  ApiAnnouncementsRoute._addFileChildren(ApiAnnouncementsRouteChildren)

interface ApiMentorsSessionsRouteChildren {
  ApiMentorsSessionsIdRoute: typeof ApiMentorsSessionsIdRoute
}

const ApiMentorsSessionsRouteChildren: ApiMentorsSessionsRouteChildren = {
  ApiMentorsSessionsIdRoute: ApiMentorsSessionsIdRoute,
}

const ApiMentorsSessionsRouteWithChildren =
  ApiMentorsSessionsRoute._addFileChildren(ApiMentorsSessionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAnnouncementsRoute: ApiAnnouncementsRouteWithChildren,
  ApplyMentorRoute: ApplyMentorRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  ApiAdminMentorsRoute: ApiAdminMentorsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminStudentsRoute: ApiAdminStudentsRoute,
  ApiApplicationsMentorRoute: ApiApplicationsMentorRoute,
  ApiMentorsDirectoryRoute: ApiMentorsDirectoryRoute,
  ApiMentorsSessionsRoute: ApiMentorsSessionsRouteWithChildren,
  ApiRegisterStudentRoute: ApiRegisterStudentRoute,
  ApiMentorsProfileUserIdRoute: ApiMentorsProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
